#!/usr/bin/env bash
set -e

CMD="$1"
NAME="$2"
shift 2

TAG="<up-to-you>"

check_image() {
  gcrane manifest "$TAG" &>/dev/null
}

publish_image() {
  local build_dir="$1"

  # Intermediate file is used because gcrane is unable to read layer from the pipe:
  #
  # > Error: writing output "ridge-auth.img": unable to calculate manifest: value not computed until stream is consumed
  tar -C "$build_dir" -cf "$build_dir.tar" .

  gcrane append --output "$build_dir.img" --new_layer "$build_dir.tar" --new_tag "$TAG"
  gcrane push "$build_dir.img" "$TAG"
}

case "$CMD" in
  check)
    check_image;;
  publish)
    publish_image "$@";;
  *)
    exit 2;;
esac
