#!/usr/bin/env bash

ONCE_STAMP="$BOX_DATA_DIR/once/$2"

trap '' SIGINT SIGQUIT

log="$1"
window="$2"
tmux_window_id=$(tmux list-panes -t "$TMUX_PANE" -F "#{window_id}")
shift 2

while ! [ -f "$ONCE_STAMP" ]; do
  clear
  echo "Current directory is $PWD"
  echo "Running $*"
  echo

  bash -xe "$@" 2>&1 | tee -a "$BOX_LOG_DIR/$log.log" | _build/workspace/bin/log-filter
  C=${PIPESTATUS[0]}

  if [[ $C -eq 0 ]]; then
    touch "$ONCE_STAMP"
    tmux rename-window -t "$tmux_window_id" "#[fg=black,bg=yellow]$window#[fg=default,bg=default]"
    # Workaround for tmux 2.9a which doesn't support set-option -p
    if ! tmux set-option -p -t "$TMUX_PANE" remain-on-exit on &>/dev/null; then
      echo
      echo "<<exited with code 0>>"
      echo
      while true; do
        sleep 1000
      done
    fi
    exit 0
  fi

  tmux rename-window -t "$tmux_window_id" "#[bg=red]$window#[bg=default]"
  echo
  echo "<<exited with code $C>>"
  echo
  read -srp "Press Enter to restart"
  tmux rename-window -t "$tmux_window_id*" "$window"
done
