#!/usr/bin/env bash

trap '' SIGINT SIGQUIT

help() {
  echo "  Welcome to Box."
  echo
  cat tools/box/static-help.txt
}

# Various operating systems set LESS in their rc-files, including such options
# as --quit-at-eof and --quit-if-one-screen that would cause busy loop below.
unset LESS

while :; do
  if ! help | less; then
    read -srp "Press Enter to restart"
  fi
done
