#!/bin/bash

#
# Let this script continue if user interrupts the application inside
#
trap '' SIGINT SIGQUIT

log="$1"
window="$2"
tmux_window_id=$(tmux list-panes -t "$TMUX_PANE" -F "#{window_id}")
shift 2

while :; do
  clear
  echo "Current directory is $PWD"
  echo "Running $*"
  echo

  #
  # Run the service and store its logs in a central location
  #
  /bin/bash -xe "$@" 2>&1 | tee -a "$TA_LOG_DIR/$log.log"
  C=${PIPESTATUS[0]}

  color=bg=red
  if [[ $C -eq 0 ]]; then
    color=fg=black,bg=yellow
  fi
  tmux rename-window -t "$tmux_window_id" "$window""#[$color][exited]#[fg=default,bg=default]"
  echo
  echo "<<exited with code $C>>"
  echo
  read -srp "Press Enter to restart"
  tmux rename-window -t "$tmux_window_id" "$window"
done
