#!/bin/bash

#
# Let this script continue if user interrupts the application inside
#
trap '' SIGINT SIGQUIT

help() {
  echo "  Welcome to test application for interactive development."
  echo
  echo "  URL:             http://127.0.0.1:8080/"
  echo
  cat static-help.txt
}

# Various operating systems set LESS in their rc-files, including such options
# as --quit-at-eof and --quit-if-one-screen that would cause busy loop below.
unset LESS

while :; do
  if ! help | less; then
    read -srp "Press Enter to restart"
  fi
done
