#!/bin/bash
set -ex

# A replacement for 'go run' that keeps the result code
# See https://github.com/golang/go/blob/master/src/cmd/go/internal/run/run.go#L40

name="$1"
shift

go build -o "$TA_RUNTIME_DIR/$name" .

exec "$TA_RUNTIME_DIR/$name" "$@"
